### ISSUE TITLE
composer.json misses dependency on Neos

### ISSUE THREAD

**Issue by mrimann** [cvette/neos-lipsum#1]
Hi

Your composer.json just mentions flow as a depencency, but I guess since it's a Neos specific package, you should rather depend on Neos (+ some specific version(range) of it).

Cheers,
Mario

**Comment by cvette** [comment]
Thanks for your suggestion. I changed the requirements to Neos versions >= 2.0 (3a6f15a9cbbc74a596577c89f0aa890d681c4012). I haven't tested earlier versions.

**Comment by mrimann** [comment]
thanks!
